### ISSUE TITLE
Update pre_treatment syntax

### ISSUE THREAD

**Issue by tdsmith** [mozilla/jetstream-config#10]
After https://github.com/mozilla/jetstream/pull/290 lands the docs here should be updated to reflect the new syntax.

Instead of being specified like

```toml
[metrics.spam.statistics.bootstrap_mean]
pre_treatments = ["drop_nulls", "log"]
```

we should write pre_treatments like

```toml
[metrics.spam.statistics.bootstrap_mean]
pre_treatments = [
  {name = "log", base = 10},
  {name = "drop_nulls"},
]
```
